### PR TITLE
Add table for service instances

### PR DESCRIPTION
**Pull request by Ladas**
Add table for service instances. We need the service instances
modeled to be able to do service retirement.

### CODE REVIEW

**Comment by Ladas** [comment]
@miq-bot assign @agrare 
@miq-bot add_label enhancement

**Comment by Ladas** [comment]
@gmcculloug @gtanzillo @agrare so we've talked with @syncrou and without this modeled, we are not able to retire the services.

**Comment by gmcculloug** [comment]
@Ladas Totally understand, the current effort we are working on is purely focused on ordering.  While we do not have an immediate need for this data I suspect we (or someone) will in the future.  Likely, the near future.

**Comment by Ladas** [comment]
so, do we have better naming than service_instance?

**Comment by agrare** [comment]
@syncrou what do you think of the name?

**Comment by Ladas** [comment]
@bdunne can you add the API also for ```service_instances``` ?

**Pull request merged**
