### PR TITLE
Update orchestration template types

### PR DESCRIPTION
**Pull request by bzwei**
Migrate 
`OrchestrationTemplateCfn` to `ManageIQ::Providers::Amazon::CloudManager::OrchestrationTemplate`
`OrchestrationTemplateHot` to `ManageIQ::Providers::Openstack::CloudManager::OrchestrationTemplate`
`OrchestrationTemplateAzure` to `ManageIQ::Providers::Azure::CloudManager::OrchestrationTemplate`
`OrchestrationTemplateVnfd` to `ManagerIQ::Provders::Openstack::CloudManager::VnfdTemplate`

https://bugzilla.redhat.com/show_bug.cgi?id=1417021

It has dependencies on ~~https://github.com/ManageIQ/manageiq-providers-azure/pull/111~~, ~~https://github.com/ManageIQ/manageiq-providers-openstack/pull/76~~, ~~https://github.com/ManageIQ/manageiq-providers-amazon/pull/286~~

### CODE REVIEW

**Comment by bzwei** [comment]
@miq-bot assign @Fryguy

**Comment by Fryguy** [comment]
Do you have a down migration?

**Comment by bzwei** [comment]
@Fryguy down migration and spec added.

**Comment by gmcculloug** [comment]
@Fryguy PTAL

**Pull request merged**
