### PR TITLE
Add columns for mw domain entities in event streams table

### PR DESCRIPTION
**Pull request by israel-hdez**
This will enable logging timeline events for middleware domain entities.

Jira: https://issues.jboss.org/browse/HAWKULAR-1249

### CODE REVIEW

**Comment by israel-hdez** [comment]
@miq-bot add_label providers/middleware

**Comment by israel-hdez** [comment]
@josejulio, can you give a look at this? And, probably, a quick look to the related PRs so that you have enough elements to approve this one to be merged.

**Comment by josejulio** [comment]
LGTM

**Comment by israel-hdez** [comment]
Thanks @josejulio.
@Fryguy This is ready to merge !

**Pull request merged**
