### PR TITLE
Allow Rails 5.1

### PR DESCRIPTION
**Pull request by chrisarcand**
For https://github.com/ManageIQ/manageiq/issues/15036

### CODE REVIEW

**Comment by chrisarcand** [comment]
@miq-bot assign @Fryguy

**Comment by Fryguy** [comment]
This seems to have added a ton of Hakiri warnings.  Anything we can do about it?

**Comment by chrisarcand** [comment]
@Fryguy I have no idea, I don't think so. Note that all the warnings I've clicked on are issues that are solved in all the versions of Rails this gemspec allows... 3.2+ ???? ¯\\\(°_o)/¯

**Comment by chrisarcand** [comment]
💩

**Comment by Fryguy** [comment]
Got a response from Hakiri and they made a change on their side...but trying to find a way to rekick the PR?

Maybe you can just rebase and repush?

**Comment by chrisarcand** [comment]
💩

**Comment by juliancheal** [comment]
@Fryguy want me to recreate this PR so we can rebase?

**Comment by juliancheal** [comment]
@chrisarcand oh hai friend!

I have created an issue tracker in your honour for 5.2. However I don't know what the plan is. And even with 5.2 we'd need to update this repo anyway :)

**Pull request closed without merging**
