### PR TITLE
Add description_string to MiqGroup

### PR DESCRIPTION
**Pull request by jvlcek**
This PR adds a description text string to MiqGroup.

Doing this will provide the backend work needed to allow the front end to add support for
this  RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1784243

### CODE REVIEW

**Comment by jvlcek** [comment]
@miq-bot add_label enhancement

**Comment by jvlcek** [comment]
@miq-bot assign @kbrock

**Comment by kbrock** [comment]
@miq-bot assign @Fryguy

**Comment by jvlcek** [comment]
@h-kataria FYI

**Comment by jvlcek** [comment]
I will rename `description_string` to `detailed_description` based on a discussing with @gtanzillo, who rightfully felt that `description` and `description_string` are ambiguous.

**Pull request merged**
