### PR TITLE
Add tables for v2v migration

### PR DESCRIPTION
**Pull request by bzwei**
https://github.com/ManageIQ/manageiq-design/issues/36

### CODE REVIEW

**Comment by bzwei** [comment]
@miq-bot assign @Fryguy 
cc @gmcculloug

**Comment by Fryguy** [comment]
As discussed

- drop the legit column
- index on v2v_mapping_items should be on v2v_mapping_id instead
- drop the last migration and put it into service_resource instead
- add options as json column to both tables
- change the names to transformation_mappings and transformation_mapping_items  (don't forget the file names)

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit c3d2c7c15e7cb634559c8ddbd8817f29c9cb7c5a
Author: Jason Frey <fryguy9@gmail.com>
Date:   Thu Jan 18 16:27:42 2018 -0500

    Merge pull request #149 from bzwei/v2v_schema
    
    Add tables for v2v migration
    (cherry picked from commit 69e98a69cba8eee9fab87928cc54005bdf87f96a)
```

**Comment by gmcculloug** [comment]
@miq-bot add_label transformation

**Pull request merged**
