### PR TITLE
Move the db:check_schema task to the public tasks.rake file

### PR DESCRIPTION
**Pull request by carbonin**
This will allow it to be used by users when attempting to correct column ordering issues after migrating.

https://bugzilla.redhat.com/show_bug.cgi?id=1508537

### CODE REVIEW

**Comment by carbonin** [comment]
@miq-bot add_label bug
@miq-bot assign @Fryguy

**Comment by carbonin** [comment]
@miq-bot add_label gaprindashvili/yes, blocker

**Comment by Fryguy** [comment]
cc @simaishi

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 828d50c74f4b772d7ed57e78d9a94f14244c866a
Author: Jason Frey <fryguy9@gmail.com>
Date:   Mon Nov 13 15:52:26 2017 -0500

    Merge pull request #124 from carbonin/make_schema_check_and_write_public
    
    Move the db:check_schema task to the public tasks.rake file
    (cherry picked from commit ad336bd67a970b12d29a74295881fcf7a4b5895f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1513143
```

**Comment by carbonin** [comment]
@simaishi I assume you didn't mean to add `gaprindashvili/no` here, right?

**Comment by simaishi** [comment]
Oops. I'm glad someone is paying attention 😄  Thanks for catching.

**Pull request merged**
