### PR TITLE
Enable PhysicalStorage inside PhysicalChassis

### PR DESCRIPTION
**Pull request by EsdrasVP**
This PR is able to:
- Enable PhysicalStorage inside PhysicalChassis by storing chassis ID in storage schema

### CODE REVIEW

**Comment by EsdrasVP** [comment]
@miq-bot assign @Fryguy

**Comment by Fryguy** [comment]
LGTM, @agrare?

**Comment by agrare** [comment]
LGTM too :+1:

**Comment by martinpovolny** [comment]
ping @Fryguy : please, merge

**Comment by EsdrasVP** [comment]
@Fryguy could you merge this?

**Comment by EsdrasVP** [comment]
@Fryguy Fixed it, now there is a separate migration for it.

**Pull request merged**
