### PR TITLE
Add requests and limits to Persistent Volume Claim

### PR DESCRIPTION
**Pull request by zakiva**
Related PRs: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/116, https://github.com/ManageIQ/manageiq/pull/16026

@miq-bot add_label enhancement

@simon3z @zeari Please review

### CODE REVIEW

**Comment by Fryguy** [comment]
@zakiva @simon3z I'm ok with this, but why is this modeled as a serialized Hash as opposed to fully modeled out?  Will we ever want it more modeled out in the future?

**Comment by simon3z** [comment]
> Will we ever want it more modeled out in the future?

@zakiva can you reference the relevant BZ in the description? I wonder if indeed we want to model that now.

**Comment by zakiva** [comment]
> @zakiva can you reference the relevant BZ in the description? I wonder if indeed we want to model that now.

I didn't find a relevant BZ for that (maybe @Loicavenel knows if we have one).
Anyway, this is part of the storage for chargeback feature @zeari is working on. We currently collect only the actual capacity of the pvc's bounded volume, which also saved as  a serialized hash and been accessed in some places, [here](https://github.com/ManageIQ/manageiq/pull/15973/files#diff-b0d42d6c800ea62f58c6e0c68ae483adR6) for example.

**Comment by zakiva** [comment]
@simon3z Do you want to merge this before the freeze?

**Comment by Loicavenel** [comment]
@zakiva @zeari can you tell me what is this PR is about? I am not sure I understand it. Is it to have Chargeback for VolumeS?

**Comment by zeari** [comment]
>@zakiva @zeari can you tell me what is this PR is about? I am not sure I understand it. Is it to have Chargeback for VolumeS?

@loicavenel yes.

**Comment by Loicavenel** [comment]
@zeari can you be more explicite? We do have PV and the Size... this is fixed.. how it can be wrong?

**Comment by zakiva** [comment]
> @zeari can you be more explicite? We do have PV and the Size... this is fixed.. how it can be wrong?

@Loicavenel The claim can have 3 different values related to the storage size: 
1. allocated - this is the actual allocated storage of the bounded volume. 
2. requested - the requested size by the claim, this is a lower bound for the allocated size. 
3. limit - upper bound. 

We currently persist only the first one, this PR adds the other two.

**Comment by zeari** [comment]
> @zeari can you be more explicite? We do have PV and the Size... this is fixed.. how it can be wrong?

The capacity we are currently listing is the size of PV that was assigned to a pod\project instead of how much the claim asked for. If you request 1GB volume, you might be assigned a 2GB volume since that is the volume closest to the size to what you ask. So the size we know about would be 2GB instead if what was actually requested.
It makes more sense to charge for what someone asked for instead of what they were *upgraded* to.
@zakiva @simon3z Correct me if im wrong.

**Comment by Loicavenel** [comment]
@zeari so, Openshift is rounding up to the closest higher GB?

**Comment by zeari** [comment]
The process AFAIK
1) a project\pod requests a PV of size x
2) openshift has PVs of size 1GB, 2GB, 3GB...
3) openshift finds a PV with a size closest to x and binds it to that project

**Comment by Loicavenel** [comment]
I look in the doc here: https://docs.openshift.com/container-platform/3.5/dev_guide/compute_resources.html.. I don't see anything in Limits regarding PV storage. But I see it in Quota... requests.storage.
Where the PoD request will come from? how do we know what was requested?

**Comment by zakiva** [comment]
> I look in the doc here: https://docs.openshift.com/container-platform/3.5/dev_guide/compute_resources.html.. I don't see anything in Limits regarding PV storage. But I see it in Quota... requests.storage.

These limits/quotas are in project level (summary of resources used in the project). The requested storage in this PR is per specific Persistent Volume Claim which represents a specific user request for storage, e.g. one pod needs 1GB.

**Comment by zakiva** [comment]
@Fryguy PTAL

**Pull request merged**
