### PR TITLE
Delete old Workflow/WorkflowInstance tables

### PR DESCRIPTION
**Pull request by agrare**
Depends on:
- [x] https://github.com/ManageIQ/manageiq-schema/pull/688
- [x] https://github.com/ManageIQ/manageiq-api/pull/1224
- [x] https://github.com/ManageIQ/manageiq/pull/22503

### CODE REVIEW

**Comment by kbrock** [comment]
this looks great. think it is a simple ci issue:

```
If this spec failed and a new migration was added that adds/removes a table,
please run `spec:table_list` to ensure that `table_list.txt` is up to date with the newest schema.
```

**Comment by agrare** [comment]
@miq-bot cross-repo-tests https://github.com/ManageIQ/manageiq-api/pull/1224 https://github.com/ManageIQ/manageiq/pull/22503, manageiq-provider-workflows

**Comment by kbrock** [comment]
may need to migrate/ remove from settings?
(not sure if they were in the db long enough)

- embedded_workflow_instance_show_list
- embedded_workflow_instance_view
- embedded_workflow_show_list
- embedded_workflow_view

**Comment by kbrock** [comment]
I think I'm getting server roles, which live in settings, and user roles confused.
These are not being migrated to other roles, but are rather going away.

**Comment by Fryguy** [comment]
> I believe deleted product features will just be removed on the next seed, @Fryguy ?

Not sure - we'll find out :)

**Comment by agrare** [comment]
> > I believe deleted product features will just be removed on the next seed, @Fryguy ?
> >
> Not sure - we'll find out :)

Forgot to update, yes they are

```
>> MiqProductFeature.pluck(:identifier).select { |id| id.start_with?("embedded_workflow") }
["embedded_workflow_automation_manager",
 "embedded_workflow",
 "embedded_workflow_view",
 "embedded_workflow_show_list",
 ...
```

`$ rails db:seed`

```
>> MiqProductFeature.pluck(:identifier).select { |id| id.start_with?("embedded_workflow") }
=> []
```

**Pull request merged**
