### PR TITLE
Remove Middleware Hawkular Schema

### PR DESCRIPTION
**Pull request by aljesusg**
Remove all schema of Middleware hawkular and models.

Per BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1526791

### CODE REVIEW

**Comment by aljesusg** [comment]
@miq-bot wip, add_label providers/middleware, cleanup, gaprindashvili/no

**Comment by aljesusg** [comment]
@miq-bot add_label wip, providers/middleware, cleanup, gaprindashvili/no

**Comment by bdunne** [comment]
@aljesusg Can you include a data migration to destroy all of the STI subclass records too?

**Comment by aljesusg** [comment]
Ok @bdunne About this... in https://github.com/ManageIQ/manageiq/pull/16791 @agrare told us about remove or not fixtures about Middleware. But He didn't see any change in migrations about db/fixtures. Should I remove fixtures too?

**Comment by agrare** [comment]
@aljesusg I think what @bdunne means is remove any records that are in tables that are still around (e.g. ext_management_systems) that have class names (e.g. ManageIQ::Providers::Hawkular::MiddlewareManager) which would break once those model names ~~are~~ were removed

**Comment by aljesusg** [comment]
Yes I know @agrare, my point is if we can remove to the fixtures related with Middleware.

**Comment by agrare** [comment]
Ah okay sorry, yeah I don't think we need to do anything here in terms of a migration for fixtures but maybe @bdunne knows for sure

**Comment by bdunne** [comment]
I don't know if any of those features need to be removed.  Maybe @jrafanie knows?

**Comment by jrafanie** [comment]
> Ok @bdunne About this... in ManageIQ/manageiq#16791 @agrare told us about remove or not fixtures about Middleware. But He didn't see any change in migrations about db/fixtures. Should I remove fixtures too?

Yes, I believe we should delete rows for `miq_product_features`, `miq_shortcuts`, `miq_user_roles`, `notification_types` that were only used for middleware and are now unused.

**Comment by kbrock** [comment]
Do we want to remove ems rows as well?

My database is having troubles because it can not find the hawkular classes defined in `ext_management_systems.type`

**Comment by aljesusg** [comment]
Ok, I am waiting until all Hawkular MW UI and models remove.

@abonas How is the state for this? Should I finish this?

**Comment by djberg96** [comment]
https://github.com/ManageIQ/manageiq/pull/19378

**Comment by Fryguy** [comment]
@djberg96 Do we need any data migrations for things like the product/live_metrics stuff?

**Comment by djberg96** [comment]
@Fryguy Looking at those files, potentially remove some `Settings.supported_metrics` I suppose. Looking at those files, I'm a little confused as to how those manifest exactly, and so how to remove them.

**Comment by Fryguy** [comment]
@djberg96 Is this ready to unwip?  If so, can you do another round of cross_repo tests with this...particularly with UI and API repos?

**Comment by djberg96** [comment]
https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/25

**Comment by agrare** [comment]
@djberg96 I am going to rebase this and update the timestamps

**Comment by agrare** [comment]
@djberg96 cross repo test are green, take this out of WIP when you're ready

**Comment by djberg96** [comment]
@miq-bot remove_label wip

**Comment by djberg96** [comment]
@agrare Ok, removed it from github, though only @aljesusg (or an admin?) can remove it from the title I think.

**Comment by agrare** [comment]
> miq-bot changed the title [WIP] Remove Middleware Hawkular Schema Remove Middleware Hawkular Schema 29 minutes ago

:)

**Comment by djberg96** [comment]
Aha, the bot updated that too, cool.

**Pull request merged**
