### PR TITLE
Add VMware folder types.

### PR DESCRIPTION
**Pull request by lfu**
Part of https://github.com/ManageIQ/manageiq/pull/17519.

https://bugzilla.redhat.com/show_bug.cgi?id=1090957

@miq-bot add_label gaprindashvili/no, enhancement

### CODE REVIEW

**Comment by Fryguy** [comment]
@agrare Can you verify this?  Do other providers use folder STI?  I would think we'd have to fix them all at once, but then I'm confused about which ones do and don't use STI.

**Comment by agrare** [comment]
@Fryguy The other STI used for folders are `Datacenter < EmsFolder` and `StorageCluster < EmsFolder`.  (And `ManageIQ::Providers::AutomationManager::InventoryGroup < EmsFolder` which is a new one to me).

Ovirt uses the base `EmsFolder` type: https://github.com/ManageIQ/manageiq-providers-ovirt/blob/master/app/models/manageiq/providers/redhat/infra_manager/refresh/parse/parser.rb#L709-L710
Same with SCVMM: https://github.com/ManageIQ/manageiq-providers-scvmm/blob/master/app/models/manageiq/providers/microsoft/infra_manager/refresh_parser.rb#L593

I'll test this out with all three providers added.

**Comment by agrare** [comment]
@miq-bot assign @Fryguy

**Comment by gmcculloug** [comment]
@agrare Is this data migration really needed or will it happen naturally as part of a provider refresh?  The feature that is using this data will be part of the next release so I would think a full provider refresh would happen as part of the upgrade to the next version.

**Comment by agrare** [comment]
@gmcculloug we don't update the type as part of EmsRefresh so existing folders will not have their types updated.

**Comment by lfu** [comment]
Add new method to ```VM``` instead of ```EmsFolder```. Keep ```EmsFolder``` untouched.

**Pull request closed without merging**
