### PR TITLE
Drop Container Component Statuses

### PR DESCRIPTION
**Pull request by zakiva**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1485431

### CODE REVIEW

**Comment by zakiva** [comment]
@simon3z @cben @zeari Please review

**Comment by zakiva** [comment]
@miq-bot add_label cleanup

**Comment by cben** [comment]
Please describe in which order those should be merged.

**Comment by simon3z** [comment]
@zakiva @cben @moolitayer do we want to remove this down to the schema (as this PR is doing) or do we think that keeping it would be nice if in the future it is properly implemented on the OpenShift side?

I am OK to remove this (also because future implementation is not laid out yet) but I also know that this is a nice OpenShift feature that may be scheduled for one of the upcoming releases.

**Comment by moolitayer** [comment]
I don't have a strong preference. :+1: to remove.

I think this PR depends on https://github.com/ManageIQ/manageiq/pull/16055 (removing the class definition)

**Comment by cben** [comment]
I also lean towards removing.
But schema is special, because re-adding it won't be backportable.  Is there chance we'll want to re-add it in z-streams?

**Comment by simon3z** [comment]
> But schema is special, because re-adding it won't be backportable. Is there chance we'll want to re-add it in z-streams?

@cben no chance but also deleting it in this release to re-add it next release seems an overhead (although, again, we do not have details on the future implementation, we may have to add many new fields).

**Comment by Fryguy** [comment]
I'm ok with deleting now and adding back later.  There's a good chance you'll have different columns anyway.

**Pull request merged**
